### ISSUE TITLE
Simple example errors

### ISSUE THREAD

**Issue by yazonnile** [SnakeskinTpl/snakeskin-loader#2]
Hi there!

webpack

``` js
{
    test: /\.ss$/,
    exclude: /node_modules/,
    loader: 'snakeskin-loader?localization=false&exec=true'
}
```

index.js

``` js
import template from './template.ss';
```

template.ss

```
- namespace demo
- template helloWorld(name = 'world')
    < .hello style = color: blue
        Hello {name}!
```

get an error

```
Uncaught Error: Cannot find module "./template.ss"
```

If I set just

``` js
loader: 'snakeskin-loader'
```

get this

```
 Cannot find module "fs"
```

Do you have simple in browser usage via webpack?

**Comment by trikadin** [comment]
```
{
    test: /\.ss$/,
    exclude: /node_modules/,
    loader: 'snakeskin?localization=false&exec=true'
}
```

If you set "execute" flag, you'll get HTML as a result, so you need html-loader after snakeskin-loader.

**Comment by trikadin** [comment]
You can see example here:
https://github.com/SnakeskinTpl/snakeskin-loader/tree/master/examples/simple

**Comment by yazonnile** [comment]
ok. So what should I do, if I need precompile template in browser?
As I understood, I should remove exec flag. Ok.
But now I have an error

```
Uncaught Error: Cannot find module "fs"
```

**Comment by trikadin** [comment]
Can you attach archive with your test project?

**Comment by yazonnile** [comment]
[ss-test.zip](https://github.com/SnakeskinTpl/snakeskin-loader/files/153333/ss-test.zip)

**Comment by trikadin** [comment]
@yazonnile I kinda modified your example, and now it works properly. 
[ss-test.zip](https://github.com/SnakeskinTpl/snakeskin-loader/files/153393/ss-test.zip)

Run `npm install` in unpacked folder to install dependencies, then `webpack` to build it, and open index.html to see result :)

**Comment by yazonnile** [comment]
oh! Thx a lot. That's a good example. BUT :)
What about to remove this

``` html
<script src="./node_modules/snakeskin/dist/snakeskin.live.min.js"></script>
```

from index.html file? I dont want any other files except my bundle files.

**Comment by trikadin** [comment]
@yazonnile, snakeskin require minimal configuration script for proper execution -- for example, if you want to use filters, you should add with Snakeskin.importFilters().

You can require it from your entry file (index.js) instead of including it via html-file.

**Comment by yazonnile** [comment]
yes. But the problem is, that I still need to include it via specific full path like 

```
require("./../../node_modules/snakeskin/dist/snakeskin.live.min.js");
```

It's kind of creepy :)
All I want - make a simple import "snakeskin" and work with imported instance.

```
import Snakeskin from 'snakeskin';
import { demo } from './template.html'; // via ss-loader

document.body.innerHTML = demo.helloWorld('Slava');

// or without ss-loader, and with raw loaded template content

import Snakeskin from 'snakeskin';
import template from './template.html';

const { demo } = Snakeskin.compile(template); // not sure about compile method. Just for example
document.body.innerHTML = demo.helloWorld('Slava');
```

**Comment by kobezzza** [comment]
Stop guys, just add webpack alias :smile: 

``` js
var path = require('path');

module.exports = {
    entry: [ './index' ],

    output: {
        path: path.join(__dirname, 'dist'),
        filename: 'index.build.js'
    },

    resolve: {
        alias: {
            // Alias to ss.live
            'snakeskin': path.join(__dirname, 'node_modules/snakeskin/dist/snakeskin.live.min.js') 
        }
    },

    module: {
        loaders: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                loader: 'babel',
                query: {
                    presets: ["es2015-node5"]
                }
            },

            {
                test: /\.ss$/,
                loader: 'snakeskin?module=cjs' // And set commonjs modules
            }
        ]
    },

    watch: true
};
```

And remove `<script src="./node_modules/snakeskin/dist/snakeskin.live.min.js"></script>` from index.html.

Thanks for your interest for the project. Unfortunately documentation for the new version of the language is not ready yet, but I'm working on it.

**Comment by yazonnile** [comment]
Yep. Alias works fine for the moment. But in the future will be great to have possibility work without such a hardcode :)

Thx a lot. Works fine for me.

**Comment by yazonnile** [comment]
Oh. One more. What is the best way to highlight ss syntax?

**Comment by kobezzza** [comment]
> Oh. One more. What is the best way to highlight ss syntax? 

I am using WebStorm with custom syntax highlight 
![snakeskin webstorm](https://4.downloader.disk.yandex.ru/disk/1f3df53fd3dec0968963f6b39953146d1d8d83c9e4cec177b010dd3f909012fd/56d64e72/zVHwkXh8EIiy0fGpiaIgod79YX7uwEHcuPlxX9Gdq0i2M7sjmMH9Q60wUyZ7T7wa7KabL6vU2ncc89zMkP8xHQ%3D%3D?uid=0&filename=2016-03-02%2001-20-00%20%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&fsize=47716&hid=90d6df4e6985d222e3266d53a8c0da16&media_type=image&tknv=v2&etag=f393fda98cda8ca300efb43607f179d2)

**Comment by yazonnile** [comment]
Yes. Try too)
thx

**Comment by trikadin** [comment]
@yazonnile you can use this config (just import the .jar file in WS)
[ss-file-type.zip](https://github.com/SnakeskinTpl/snakeskin-loader/files/153885/ss-file-type.zip)
