### ISSUE TITLE
В bem-фильтр не приходит аргумент attrs при использовании exec

### ISSUE THREAD

**Issue by trikadin** [SnakeskinTpl/snakeskin-loader#3]
Собственно, сабж. Если выполнять шаблоны сразу при компиляции, то в фильтр bem приходят только & и то, что после.

![Логирование](https://cloud.githubusercontent.com/assets/1655230/17391072/c5f05618-5a1b-11e6-842e-09c5eeae1ae6.png)

**Comment by kobezzza** [comment]
Не понял, т.е. & заменяется на пустое место? Ты уверен, что у тебя последняя версия СС?

**Comment by kobezzza** [comment]
Если ты переопределял фильтр, то скорее всего ты забыл, что:

1) Всё это нужно делать до вызова SS;
2) Написать биндинг атрибутов (для этого нужно было посмотреть как этот фильтр определён):

```
Snakeskin.setFilterParams('bem', {
    bind: [(o) => o.getVar('__ATTR_CACHE__')]
});
```
